### ISSUE TITLE
Doesn't work with filterBy

### ISSUE THREAD

**Issue by andre-dw** [TahaSh/vue-paginate#2]
If using filterBy the paginate function still thinks it shows 6 items if v-paginate:6 is specified but because filterBy removes some of the items it shows less.
Any working around or fix for this?

**Comment by TahaSh** [comment]
Thanks @andre-dw for mentioning this, I wasn't aware of it :).

So, I've just published a new release for this plugin that includes a method called `refresh+[listName]+page`. When you call this method, the content of your paginated list will update.

You have only two more steps to use *filterBy* with *vue-paginate*:

First, use the filter in `v-paginate` directive. Like this:

``` js
<ul v-paginate:3="langs | filterBy language">
```

In this case, I assume that you have some input with a `v-model="language"` — which you'd use for filtering.

Finally, you just need to call the refresh method whenever the filtering value changes. So, typically you would use it with the `@keyup` event. Like this:

``` html
<input type="text" v-model="language" @keyup="refreshLangsPage">
```

That's it! I hope this solved your problem :).

**Comment by andre-dw** [comment]
Thanks for the quick response.

This doesn't really fix it.
It still doesn't show the full list of 6.

I have some default filters on the object for items that needs to be hidden all the time.
The hidden items are in the [listName] object but as expected not in the list that displays on the page.

**Comment by TahaSh** [comment]
Sorry, but could you please elaborate further with some code? Just to confirm I understand what you want.

**Comment by andre-dw** [comment]
`<div class="carpark-listings" v-if="!searching" v-paginate:6="listings">
    <div    class="carpark-listing"
               v-for="listing in listings | orderBy sortKey |
                          filterBy '3' in 'acceptance_status' |
                          filterBy '0' in 'coming_soon'">
    </div>
       {{ title }}
 </div>`

This is the code i'm using as html template.
The object 'listings' is just a list of objects with a lot of data in it.
The filterBy is always on because i want some items hidden by default.

If i do this the first page only shows 3 items because the other 3 are filtered out of the list but are in the [listName] object vue-paginate create.

**Comment by TahaSh** [comment]
Aha, the problem is that you're applying the filter in the `v-for`. In my answer, I've mentioned that you should use it in the `v-paginate` directive instead. Like this:

``` html
<div class="carpark-listings" v-if="!searching" v-paginate:6="listings | orderBy 'sortKey' | filterBy '3' in 'acceptance_status' | filterBy '0' in 'coming_soon'">
    <div class="carpark-listing" v-for="listing in listings">
<!-- ... -->
```

Tell me if this solves it :).

**Comment by andre-dw** [comment]
Aha, that solved it!
Thanks!

Maybe you can also add a currentPage value to show on which page you are and to show or hide the next/previous button.
